FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia o projeto primeiro
COPY ./MatuTI.csproj ./

# Restore
RUN dotnet restore ./MatuTI.csproj

# Copia todo o resto do código
COPY . .

# Publish
RUN dotnet publish ./MatuTI.csproj -c Release -o /app/publish

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MatuTI.dll"]